services:
  app:
    build: .
    container_name: centralcred-app
    working_dir: /var/www
    command: sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: centralcred-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: centralcred-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: centralcred
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: centralcred
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
